name: Publish @navikt/diagnosekoder npm

on:
  push:
    branches: ["main"]
    paths:
       - "koder/**"
env:
  NODE_AUTH_TOKEN: ${{ secrets.READER_TOKEN }}

jobs:
  build:
    if: "!contains(github.event.head_commit.message, '[docs]')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://npm.pkg.github.com"
          scope: "@navikt"
      - name: Copy JSON files
        run: npm run copy-files
        working-directory: packages/npm-diagnosekoder
      - name: Publish module
        run: npm publish
        working-directory: packages/npm-diagnosekoder
        if: github.ref == 'refs/heads/main'
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  increment-version:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - name: Setup github connection for auth
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git remote set-url origin https://github-actions[bot]:$NAV_DS_TOKEN@github.com/$GITHUB_REPOSITORY.git
      - name: Increment version
        run: npm version major
        working-directory: packages/npm-diagnosekoder
      - run: git add . && git commit -m "[skip ci] bump version to $(jq -r .version packages/npm-diagnosekoder/package.json)" && git push
